### ISSUE TITLE
Comic thumbnail display problem

### ISSUE THREAD

**Issue by huajideshutiao** [AmanoTeam/Sunny#1]
![Screenshot_2023-12-18-00-42-35-897_eu kanade tachiyomi sy](https://github.com/AmanoTeam/Sunny/assets/38980554/48754ecb-900e-42cc-a3fa-bba066f23780)
As shown in the figure, the thumbnail part is not displayed.
Client is TachiyomiSY (eu.kanade.tachiyomi.sy) 1.9.4

**Comment by Kartatz** [comment]
[app-release.zip](https://github.com/user-attachments/files/16577439/app-release.zip)

@huajideshutiao, could you please test and check if the issue persists?

**Comment by huajideshutiao** [comment]
> [app-release.zip](https://github.com/user-attachments/files/16577439/app-release.zip)
> 
> @huajideshutiao, could you please test and check if the issue persists?

The thumbnail can now be displayed normally.
