### ISSUE TITLE
Yōkai support

### ISSUE THREAD

**Issue by CleanerThanRotom-W** [AmanoTeam/Sunny#3]
[Yōkai](https://github.com/null2264/yokai), a TachiyomiJ2K fork.

**Comment by Kartatz** [comment]
[app-release.zip](https://github.com/user-attachments/files/15907171/app-release.zip)

Could you please test it?

**Comment by CleanerThanRotom-W** [comment]
![Screenshot_20240620-144552](https://github.com/AmanoTeam/Sunny/assets/98265798/56de8b56-162d-4d2d-a0a7-3a5326b4fb95)

It doesn't show up as Recommended ./

**Comment by Kartatz** [comment]
> debug's package name is eu.kanade.tachiyomi.nightlyYokai and not what you put in the most recent commit  

Thanks for pointing this.

**Comment by Kartatz** [comment]
Added in `v0.3`.
